<?php

/**
 * @file
 * The OpenEuropa Agenda module file.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function oe_agenda_theme(): array {
  return [
    'oe_agenda' => [
      'render element' => 'elements',
    ],
    'oe_agenda_day' => [
      'render element' => 'elements',
    ],
    'oe_agenda_session' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_oe_agenda(array &$variables): void {
  oe_content_entity_default_preprocess($variables, 'oe_agenda');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_oe_agenda_day(array &$variables): void {
  oe_content_entity_default_preprocess($variables, 'oe_agenda_day');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_oe_agenda_session(array &$variables): void {
  oe_content_entity_default_preprocess($variables, 'oe_agenda_session');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oe_agenda_theme_suggestions_oe_agenda(array $variables): array {
  return oe_content_entity_default_theme_suggestion($variables, 'oe_agenda');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oe_agenda_theme_suggestions_oe_agenda_day(array $variables): array {
  return oe_content_entity_default_theme_suggestion($variables, 'oe_agenda_day');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oe_agenda_theme_suggestions_oe_agenda_session(array $variables): array {
  return oe_content_entity_default_theme_suggestion($variables, 'oe_agenda_session');
}
