oe_agenda.oe_agenda_type.*:
  type: config_entity
  label: 'Agenda type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
oe_agenda.oe_agenda_day_type.*:
  type: config_entity
  label: 'Day type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
